# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [watch]

jobs:
  one:
    runs-on: macos-latest
    steps:
      - name: Dump GitHub event context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
          curl https://api.github.com/users/looshlee
      - name: Did anything happen in previous step?
        run: | 
          echo curl https://api.github.com/users/looshlee
