# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [watch]

jobs:
  checkout:
    
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: checkout the repo

  api-call:
     runs-on: macos-latest
    
     steps:
       - uses: actions/github-script@0.9.0
       - name: github script 
         with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.create({
              issue_number: 1,
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Issue from Actions'
            })
