# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [watch]

jobs:

  Build:
    
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: checkout the repo
        run: |
          echo ${{ toJson(github) }

      - name: api call
        run: |
          curl  -X GET -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"  -H "Accept: application/vnd.github.golden-comet-preview+json" https://api.github.com/users/looshlee
            
